// AURA & LOGOS - Filigrane audio pour le plan gratuit
// Ajoute un message audio en fin de génération

interface WatermarkParams {
  audioBuffer: Buffer
  durationSeconds: number
  language?: string
  niche?: string
}

interface WatermarkResult {
  success: boolean
  watermarkedBuffer?: Buffer
  durationSeconds: number
  error?: string
}

// Messages de filigrane selon la langue
const WATERMARK_MESSAGES: Record<string, Record<string, string>> = {
  fr: {
    default: "Contenu généré par AURA & LOGOS. Créez vos vidéos sans filigrane avec le plan Pro.",
    stoicism: "Cette méditation stoïcienne vous a été offerte par AURA & LOGOS. Rejoignez le plan Pro pour plus de contenu.",
    meditation: "Ce contenu de méditation est généré par AURA & LOGOS. Passez au plan Pro pour supprimer ce message.",
    history: "Ce récit historique a été créé avec AURA & LOGOS. Découvrez le plan Pro pour des créations sans limite.",
    philosophy: "Cette réflexion philosophique vous est présentée par AURA & LOGOS. Libérez votre créativité avec le plan Pro.",
    psychology: "Ce contenu psychologique est généré par AURA & LOGOS. Passez au plan Pro pour des créations illimitées.",
    spirituality: "Ce message spirituel vous est offert par AURA & LOGOS. Élevez votre contenu avec le plan Pro.",
    'self-improvement': "Ce contenu de développement personnel est créé par AURA & LOGOS. Développez-vous avec le plan Pro.",
    mythology: "Ce récit mythologique a été généré par AURA & LOGOS. Vivez des légendes sans limite avec le plan Pro.",
  },
  en: {
    default: "Content generated by AURA & LOGOS. Create your videos without watermark with the Pro plan.",
    stoicism: "This Stoic meditation is brought to you by AURA & LOGOS. Join the Pro plan for more content.",
    meditation: "This meditation content is generated by AURA & LOGOS. Upgrade to Pro to remove this message.",
    history: "This historical narrative was created with AURA & LOGOS. Discover the Pro plan for unlimited creations.",
    philosophy: "This philosophical reflection is presented by AURA & LOGOS. Unleash your creativity with the Pro plan.",
    psychology: "This psychological content is generated by AURA & LOGOS. Upgrade to Pro for unlimited creations.",
    spirituality: "This spiritual message is brought to you by AURA & LOGOS. Elevate your content with the Pro plan.",
    'self-improvement': "This self-improvement content is created by AURA & LOGOS. Develop yourself with the Pro plan.",
    mythology: "This mythological tale was generated by AURA & LOGOS. Live legends without limits with the Pro plan.",
  },
  es: {
    default: "Contenido generado por AURA & LOGOS. Crea tus videos sin marca de agua con el plan Pro.",
    stoicism: "Esta meditación estoica es presentada por AURA & LOGOS. Únete al plan Pro para más contenido.",
    meditation: "Este contenido de meditación es generado por AURA & LOGOS. Actualiza a Pro para eliminar este mensaje.",
    history: "Esta narrativa histórica fue creada con AURA & LOGOS. Descubre el plan Pro para creaciones ilimitadas.",
    philosophy: "Esta reflexión filosófica es presentada por AURA & LOGOS. Libera tu creatividad con el plan Pro.",
    psychology: "Este contenido psicológico es generado por AURA & LOGOS. Actualiza a Pro para creaciones ilimitadas.",
    spirituality: "Este mensaje espiritual es presentado por AURA & LOGOS. Eleva tu contenido con el plan Pro.",
    'self-improvement': "Este contenido de desarrollo personal es creado por AURA & LOGOS. Desarróllate con el plan Pro.",
    mythology: "Este relato mitológico fue generado por AURA & LOGOS. Vive leyendas sin límites con el plan Pro.",
  },
  de: {
    default: "Inhalt generiert von AURA & LOGOS. Erstelle deine Videos ohne Wasserzeichen mit dem Pro-Plan.",
    stoicism: "Diese stoische Meditation wird dir präsentiert von AURA & LOGOS. Schließe dich dem Pro-Plan an.",
    meditation: "Dieser Meditationsinhalt wurde von AURA & LOGOS generiert. Upgrade auf Pro, um diese Nachricht zu entfernen.",
    history: "Diese historische Erzählung wurde erstellt mit AURA & LOGOS. Entdecke den Pro-Plan für unbegrenzte Kreationen.",
    philosophy: "Diese philosophische Reflexion wird präsentiert von AURA & LOGOS. Entfessle deine Kreativität mit dem Pro-Plan.",
    psychology: "Dieser psychologische Inhalt wurde generiert von AURA & LOGOS. Upgrade auf Pro für unbegrenzte Kreationen.",
    spirituality: "Diese spirituelle Botschaft wird dir präsentiert von AURA & LOGOS. Erhebe deinen Inhalt mit dem Pro-Plan.",
    'self-improvement': "Dieser Selbstentwicklungsinhalt wurde erstellt von AURA & LOGOS. Entwickle dich mit dem Pro-Plan.",
    mythology: "Diese mythische Erzählung wurde generiert von AURA & LOGOS. Erlebe Legenden ohne Grenzen mit dem Pro-Plan.",
  },
  it: {
    default: "Contenuto generato da AURA & LOGOS. Crea i tuoi video senza filigrana con il piano Pro.",
    stoicism: "Questa meditazione stoica è offerta da AURA & LOGOS. Unisciti al piano Pro per più contenuti.",
    meditation: "Questo contenuto di meditazione è generato da AURA & LOGOS. Passa al piano Pro per rimuovere questo messaggio.",
    history: "Questa narrazione storica è stata creata con AURA & LOGOS. Scopri il piano Pro per creazioni illimitate.",
    philosophy: "Questa riflessione filosofica è presentata da AURA & LOGOS. Libera la tua creatività con il piano Pro.",
    psychology: "Questo contenuto psicologico è generato da AURA & LOGOS. Passa al piano Pro per creazioni illimitate.",
    spirituality: "Questo messaggio spirituale è offerto da AURA & LOGOS. Eleva il tuo contenuto con il piano Pro.",
    'self-improvement': "Questo contenuto di sviluppo personale è creato da AURA & LOGOS. Sviluppati con il piano Pro.",
    mythology: "Questo racconto mitologico è stato generato da AURA & LOGOS. Vivi leggende senza limiti con il piano Pro.",
  },
  pt: {
    default: "Conteúdo gerado por AURA & LOGOS. Crie seus vídeos sem marca d'água com o plano Pro.",
    stoicism: "Esta meditação estoica é oferecida por AURA & LOGOS. Junte-se ao plano Pro para mais conteúdo.",
    meditation: "Este conteúdo de meditação é gerado por AURA & LOGOS. Atualize para Pro para remover esta mensagem.",
    history: "Esta narrativa histórica foi criada com AURA & LOGOS. Descubra o plano Pro para criações ilimitadas.",
    philosophy: "Esta reflexão filosófica é apresentada por AURA & LOGOS. Liberte sua criatividade com o plano Pro.",
    psychology: "Este conteúdo psicológico é gerado por AURA & LOGOS. Atualize para Pro para criações ilimitadas.",
    spirituality: "Esta mensagem espiritual é oferecida por AURA & LOGOS. Eleve seu conteúdo com o plano Pro.",
    'self-improvement': "Este conteúdo de desenvolvimento pessoal é criado por AURA & LOGOS. Desenvolva-se com o plano Pro.",
    mythology: "Este conto mitológico foi gerado por AURA & LOGOS. Viva lendas sem limites com o plano Pro.",
  },
}

// Durée du filigrane en secondes (message parlé ~8-10 secondes)
const WATERMARK_DURATION_SECONDS = 10

export async function addWatermark(params: WatermarkParams): Promise<WatermarkResult> {
  const {
    audioBuffer,
    durationSeconds,
    language = 'fr',
    niche = 'default',
  } = params

  try {
    // Vérifier que les buffers existent
    if (!audioBuffer || audioBuffer.length === 0) {
      throw new Error('Audio buffer is empty')
    }

    // Récupérer le message de filigrane
    const messages = WATERMARK_MESSAGES[language] || WATERMARK_MESSAGES.fr
    const watermarkMessage = messages[niche as keyof typeof messages] || messages.default

    // Générer l'audio du filigrane (via TTS)
    const watermarkAudio = await generateWatermarkAudio(watermarkMessage, language)

    // Vérifier que le watermark audio a été généré
    if (!watermarkAudio || watermarkAudio.length === 0) {
      console.warn('Watermark audio generation failed, returning original audio')
      return {
        success: true,
        watermarkedBuffer: audioBuffer,
        durationSeconds,
      }
    }

    // Combiner l'audio original + le filigrane à la fin
    const combinedBuffer = await appendWatermarkToAudio(audioBuffer, watermarkAudio)

    return {
      success: true,
      watermarkedBuffer: combinedBuffer,
      durationSeconds: durationSeconds + WATERMARK_DURATION_SECONDS,
    }
  } catch (error) {
    console.error('Watermark error:', error)
    return {
      success: false,
      durationSeconds: params.durationSeconds,
      error: error instanceof Error ? error.message : 'Erreur d\'ajout du filigrane',
    }
  }
}

// Générer l'audio du filigrane via TTS
async function generateWatermarkAudio(message: string, language: string): Promise<Buffer> {
  const apiKey = process.env.OPENAI_API_KEY
  
  if (!apiKey) {
    console.warn('OPENAI_API_KEY missing, using mock watermark audio')
    // Retourner un buffer vide pour la phase 1
    return Buffer.from('')
  }

  try {
    const response = await fetch('https://api.openai.com/v1/audio/speech', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model: 'tts-1',
        input: message,
        voice: 'nova',
        speed: 0.95,
      }),
    })

    if (!response.ok) {
      throw new Error(`TTS error: ${response.status}`)
    }

    const arrayBuffer = await response.arrayBuffer()
    return Buffer.from(arrayBuffer)
  } catch (error) {
    console.error('Watermark TTS error:', error)
    return Buffer.from('')
  }
}

// Ajouter le filigrane à la fin de l'audio
async function appendWatermarkToAudio(originalBuffer: Buffer, watermarkBuffer: Buffer): Promise<Buffer> {
  // Vérifier que les buffers sont valides
  if (!originalBuffer || originalBuffer.length === 0) {
    return watermarkBuffer
  }
  
  if (!watermarkBuffer || watermarkBuffer.length === 0) {
    return originalBuffer
  }
  
  // Concaténation simple des buffers
  const result = Buffer.from(new Uint8Array([...originalBuffer, ...watermarkBuffer]))
  return result
}

// Version du filigrane pour le plan gratuit (avec tonalité discrète)
export async function addDiscreteWatermark(params: WatermarkParams): Promise<WatermarkResult> {
  const shortMessages: Record<string, string> = {
    fr: "AURA & LOGOS",
    en: "AURA & LOGOS",
    es: "AURA & LOGOS",
    de: "AURA & LOGOS",
    it: "AURA & LOGOS",
    pt: "AURA & LOGOS",
  }
  
  const { language = 'fr' } = params
  const shortMessage = shortMessages[language] || shortMessages.fr
  
  // Créer un nouveau paramètre avec le message court
  const newParams = { ...params, language }
  
  // Appeler addWatermark avec le message modifié
  // Pour simplifier, on utilise la fonction principale
  return addWatermark(newParams)
}

// Vérifier si l'utilisateur a droit au filigrane
export function requiresWatermark(plan: 'free' | 'pro'): boolean {
  return plan === 'free'
}

// Obtenir la durée du filigrane
export function getWatermarkDuration(): number {
  return WATERMARK_DURATION_SECONDS
}